
#TacZ Additions - Server Config
[server]
	#If false, muzzle flash will not be sent to clients.
	enableMuzzleFlash = true
	#Vertical recoil multiplier for pistols
	#Range: 0.0 ~ 10.0
	recoilPistolVertical = 1.0
	#Vertical recoil multiplier for rifles
	#Range: 0.0 ~ 10.0
	recoilRifleVertical = 1.0
	#Vertical recoil multiplier for snipers
	#Range: 0.0 ~ 10.0
	recoilSniperVertical = 1.0
	#Vertical recoil multiplier for SMGs
	#Range: 0.0 ~ 10.0
	recoilSMGVertical = 1.0
	#Vertical recoil multiplier for shotguns
	#Range: 0.0 ~ 10.0
	recoilShotgunVertical = 1.0
	#Vertical recoil multiplier for RPGs
	#Range: 0.0 ~ 10.0
	recoilRPGVertical = 1.0
	#Vertical recoil multiplier for MGs
	#Range: 0.0 ~ 10.0
	recoilMGVertical = 1.0
	#Horizontal recoil multiplier for pistols
	#Range: 0.0 ~ 10.0
	recoilPistolHorizontal = 1.0
	#Horizontal recoil multiplier for rifles
	#Range: 0.0 ~ 10.0
	recoilRifleHorizontal = 1.0
	#Horizontal recoil multiplier for snipers
	#Range: 0.0 ~ 10.0
	recoilSniperHorizontal = 1.0
	#Horizontal recoil multiplier for SMGs
	#Range: 0.0 ~ 10.0
	recoilSMGHorizontal = 1.0
	#Horizontal recoil multiplier for shotguns
	#Range: 0.0 ~ 10.0
	recoilShotgunHorizontal = 1.0
	#Horizontal recoil multiplier for RPGs
	#Range: 0.0 ~ 10.0
	recoilRPGHorizontal = 1.0
	#Horizontal recoil multiplier for MGs
	#Range: 0.0 ~ 10.0
	recoilMGHorizontal = 1.0

